# .github/workflows/update-docs.yml
name: Update Documentation
on:
  push:
    branches: [main]
permissions:
  contents: write
concurrency:
  group: update-docs
  cancel-in-progress: true
defaults:
  run:
    shell: bash
jobs:
  generate-docs:
    runs-on: ubuntu-latest
    env: 
      USER_EMAIL: ${{ secrets.USER_EMAIL }}
      USER_NAME: ${{ secrets.USER_NAME }}
    steps:
      - uses: actions/checkout@v3
      - name: Generate Data Model
        run: ./reverse-engineer-bash/reverse-engineer.sh --data-model
      - name: Commit updated data model
        run: |
          git config --global user.email "${USER_EMAIL}"
          git config --global user.name "${USER_NAME}"
          git add docs/generated/
          git commit -m "Update data model from code analysis"
          git push